SRCS = \
	./CachedFile.cpp \
	./Config.cpp \
	./Cookie.cpp \
	./FileCache.cpp \
	./HttpForm.cpp \
	./HttpRequest.cpp \
	./HttpResponse.cpp \
	./HttpServer.cpp \
	./HttpThreadPool.cpp \
	./Interface.cpp \
	./PageSource.cpp \
	./PageSourceEnumerator.cpp
TOP                   = ..
LIB_OUTPUT            = libAlajarDll.so

include $(TOP)/Makefile.include
