SRCS = \
	./Algorithm.cpp \
	./ConfigFile.cpp \
	./Crypto.cpp \
	./Event.cpp \
	./File.cpp \
	./FileHeap.cpp \
	./IObject.cpp \
	./Library.cpp \
	./MemoryMappedFile.cpp \
	./Mutex.cpp \
	./OS.cpp \
	./ReadWriteLock.cpp \
	./Socket.cpp \
	./String.cpp \
	./TempFile.cpp \
	./Thread.cpp \
	./Time.cpp \
	./Variant.cpp
TOP                   = ..
LIB_OUTPUT            = libOsal.so

include $(TOP)/Makefile.include

