SRCS = \
	./Backup.cpp \
	./Database.cpp \
	./DatabaseApi.cpp \
	./DatabaseBackups.cpp \
	./DatabaseEnumerators.cpp \
	./DatabaseReload.cpp \
	./DatabaseTables.cpp \
	./DatabaseTemplates.cpp \
	./Interface.cpp \
	./ReadTable.cpp \
	./Table.cpp \
	./TableContext.cpp \
	./TableIndexing.cpp \
	./Template.cpp \
	./Transaction.cpp \
	./WriteTable.cpp
TOP                   = ..
LIB_OUTPUT            = libDatabase.so

include $(TOP)/Makefile.include
