SRCS                  = Main.cpp
TOP                   = ..
OUTPUT                = Alajar

include $(TOP)/Makefile.include

# DO NOT DELETE

Main.o: ../AlajarDll/Alajar.h ../Osal/IObject.h ../Osal/OS.h
Main.o: ../Osal/Algorithm.h ../Osal/Time.h ../Osal/Variant.h ../Osal/String.h
Main.o: ../Osal/Variant.h ../Osal/Event.h
