name: Almonaster Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Get version from tag
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build
      run: msbuild -m .\Source\Almonaster.sln /p:Configuration=Release /p:Platform=x64 

    - name: Create release directory
      run: mkdir ./Release
      shell: pwsh

    - name: Zip binaries
      run: Compress-Archive Admin.dll,Alajar.dll,Alajar.exe,AlajarSvc.exe,Almonaster.dll,Asfpp.exe,Osal.dll,SqlDatabase.dll,SqlDatabaseBridge.dll ../../../../../Release/almonaster-${{ steps.get_version.outputs.version }}-x64.zip
      shell: pwsh
      working-directory: ./Source/Drop/x64/Release/bin

    - name: Zip symbols
      run: Compress-Archive Admin.pdb,Alajar.pdb,AlajarDll.pdb,AlajarSvc.pdb,Almonaster.pdb,Asfpp.pdb,Osal.pdb,SqlDatabase.pdb,SqlDatabaseBridge.pdb ../../../../../Release/almonaster-${{ steps.get_version.outputs.version }}-x64-pdb.zip
      shell: pwsh
      working-directory: ./Source/Drop/x64/Release/bin

    - name: Zip site
      run: Compress-Archive * ../../Release/almonaster-${{ steps.get_version.outputs.version }}-site.zip
      shell: pwsh
      working-directory: ./Source/Release

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Almonaster ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload binaries
      id: upload-release-asset1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./Release/almonaster-${{ steps.get_version.outputs.version }}-x64.zip
        asset_name: almonaster-${{ steps.get_version.outputs.version }}-x64.zip
        asset_content_type: application/zip

    - name: Upload symbols
      id: upload-release-asset2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./Release/almonaster-${{ steps.get_version.outputs.version }}-x64-pdb.zip
        asset_name: almonaster-${{ steps.get_version.outputs.version }}-x64-pdb.zip
        asset_content_type: application/zip

    - name: Upload site
      id: upload-release-asset3
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./Release/almonaster-${{ steps.get_version.outputs.version }}-site.zip
        asset_name: almonaster-${{ steps.get_version.outputs.version }}-site.zip
        asset_content_type: application/zip
